# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.9" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
# different stages in the pipeline
stages:
  - Static Analysis
  - Test
  - Deploy
#defines the job in Static Analysis
pylint:
  stage: Static Analysis
  script:
  - pylint -d C0103,C0301,R0902,R0914 $(git ls-files '*.py')

pytest:
  stage: Test
  script:
  - pytest
  
MSDeploy:
  stage: Deploy
  script:
  - echo "test ms deploy"
  - cd src
  - pyinstaller -F hello.py
